name: Terraform security scan
on:
  pull_request:
  push:
    branches: main
jobs:
  tfsec-pr-commenter:
    name: tfsec PR commenter
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v6
